--
dist: focal
language: generic
sudo: required

services:
  - docker

matrix:
  fast_finish: true
  include:

     - name: "ARM DevSummit 2021 Python 3.7 on Arm64 (v8)"
       os: linux
       arch: arm64
       language: python
       python: 3.7
       before_install:
       - hostnamectl
       - python --version
       - docker --version
       install: skip
       before_script: skip
       script: skip
       env:
        - LIB_PATH="/usr/bin/shared/x86_64/v1"

     - name: "ARM DevSummit 2021 Python 3.7 on Arm64-Graviton2"
       os: linux
       arch: arm64-graviton2
       language: python
       python: 3.7
       before_install:
       - hostnamectl
       - python --version
       - docker --version
       install: skip
       before_script: skip
       script: skip
       env:
        - LIB_PATH="/usr/bin/shared/x86_64/v1"

             
before_install: skip
install: skip
script: skip
after_success: skip
